### ISSUE TITLE
Wiki update quick-perf v1

### ISSUE THREAD

**Issue by FTarfasse** [quick-perf/doc#1]
Hello Jean,

As you suggested, I tried to do a PR to this repository with the modifications I made on the markdown files from the wiki but I'm not sure you received the PR.
You can see the modifications I made in my commit [here](https://github.com/FTarfasse/doc/commit/43f16d14764319d6159ea67580be643dfbd04d1c).
I updated the main file, created an individual file for each annotation and removed unexisting ones.

To sum up the proposed changes:
- modified : SQL-annotations.md
- modified : @DisplaySqlOfTestMethodBody.md
- modified : @DisableLikeWithLeadingWildcard.md
- new file : @DisableCrossJoin.md
- new file : @DisableQueriesWithoutBindParameters.md
- new file : @EnableCrossJoin.md
- new file : @EnableQueriesWithoutBindParameters.md
- new file : @ExpectMaxInsert.md
- new file : @ExpectMaxUpdate.md
- deleted : @EnableSameSelectTypesWithDifferentParams.md (annotation does not exists as of now)
- deleted : @DisableSameSelectTypesWithDifferentParams.md (annotation does not exists as of now)

As always, this is just a starting point.

Let me know what you think !

Kind regards,
Fabrice

**Comment by jeanbisutti** [comment]
Hi Fabrice,

Many thanks!

It looks great! 

Could you please take into accounts [these feedbacks](https://github.com/FTarfasse/quickperf/commit/943fda0e34d48fe6ae911ea274b72ca18b722661)?

I can't see a diff in the updated wiki pages. Perhaps, you may clone the wiki repo in this way 
 ```git clone https://github.com/quick-perf/doc.wiki.git```
and after push it in your Github account?

So I could see the differences with the previous version.

 Otherwise, I could directly update the wikipages from [this issue](https://github.com/quick-perf/quickperf/issues/90). What do you prefer?

Kind regards,

Jean

**Comment by FTarfasse** [comment]
Hi Jean,

I took your feedbacks into account and made a new commit for issue #90. I also included them in the wiki.

Here is [my repo](https://github.com/FTarfasse/quick-perf-wiki) for the wiki where you can check the updates in my commit.

Hope this is convenient for you, I'm doing my best keeping everything in sync with Git AND being as clear as possible (with all the rebases, squash etc ...).

Kind regards,
Fabrice

**Comment by jeanbisutti** [comment]
Hi Fabrice,

Many thanks for your great work!

Until you finish to improve the SQL documentation, I will not update the SQL pages in the wiki in order to facilitate your work.

Kind regards,

Jean

**Comment by FTarfasse** [comment]
Hi Jean,

I made a [new commit](https://github.com/FTarfasse/quick-perf-wiki/commit/8598f218b7dec68675bb8f0bc0aca524ccc16b61) based on today's exchanges.
The commit shows a diff on the @DisplaySqlOfTestMethodBody.md event though I didn't change anything (on purpose at least).

Kind regards,
Fabrice

**Comment by jeanbisutti** [comment]
Hi Fabrice,

Many thanks for all the wiki improvements.

I reported them in the QuickPerf wiki.

Kind regards,

Jean

**Comment by FTarfasse** [comment]
You're welcome !
